### PR TITLE
Fix Windows support for partial references.

### PR DESCRIPTION
**Pull request by SteffanDonal**
Forces template names into POSIX form, and escapes backslashes in module names.

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
Thank you for taking time to submit this! Do you think you could add a test case?

**Comment by SteffanDonal** [comment]
Sure thing!

**Comment by SteffanDonal** [comment]
All done @alexgorbatchev !

**Comment by alexgorbatchev** [comment]
Fantastic job, thank you!

**Pull request merged**
